version: '3.7'
services:
    es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
      container_name: es
      # environment:
      #   - node.name=es
      #   - discovery.type=single-node
      volumes:
        - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
        - esnet
    kibana:
      image: docker.elastic.co/kibana/kibana:7.3.1
      container_name: kibana
      volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - 5601:5601
      networks:
        - esnet

networks:
  esnet:
